# Generated by Django 4.0.4 on 2022-05-13 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='doctor',
        ),
    ]
